### PR TITLE
fix: fixing session time duration

### LINKED ISSUE #2: Extender el tiempo de la sesion de usuario
Actualmente es de 5 minutos, pero la peticion es de extender ese tiempo de sesion para que sea mayor

### PR DESCRIPTION
**Pull request by Elias-Gill**
Replace session management with JWT-based sessions

This reduces session overhead and enables session persistence across
server restarts without additional engineering effort.

Closes #2

### CODE REVIEW

File: internal/auth/session_manager.go [hunk 1]
```diff
@@ -104,11 +81,46 @@ func SessionMiddleware(next http.Handler) http.Handler {
...
+	claims := &Claims{
+		UserID: userID,
+		RegisteredClaims: jwt.RegisteredClaims{
+			ExpiresAt: jwt.NewNumericDate(expirationTime),
+			IssuedAt:  jwt.NewNumericDate(time.Now()),
+		},
+	}
+
+	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
+	tokenString, err := token.SignedString([]byte(config.Get().Security.UpdateKey))
```
Comment (Elias-Gill) [inline internal/auth/session_manager.go]: Usar otra key diferente a UpdateKey

Comment (Elias-Gill) [reply internal/auth/session_manager.go]: Tambien deberria de solucionar el uso de zonas horarias dentro del server (tiempo de sesion de la cookie).
